name: Build Meilisync Image
on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout main
#
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        id: setup-docker-buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        run: |
          docker build --tag ghcr.io/katkinclub/meilisync:latest -f Dockerfile .
          docker push ghcr.io/katkinclub/meilisync:latest
